KeyboardInterrupt: 

In [2]:
!pip install tensorflow


In [3]:
import tensorflow as tf
print(tf.__version__)

2.19.0


In [4]:
# creation tenseur
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
scalar.ndim

0

In [7]:
vector = tf.constant([10,10])
vector.ndim

1

In [9]:
matrix = tf.constant([[10,7], [7,10]])
matrix.ndim

2

In [13]:
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor.ndim

3

In [17]:
#Tenseurs aléatoires
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3, 2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [20]:
#Melanger les données (cette fonction est appelé en arrière plan lorsque les données sont envoyés au ANN)
not_shuffled = tf.constant([[10, 7],
                             [3, 4],
                             [2, 5]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [21]:
# create tensor of 1
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [22]:
# create zeros tensor

tf.zeros(shape=(3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [23]:
# size nombre d'éléments à l'intérieur du tenseur
# shape nombre
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [24]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [25]:
# dernier element de chaque ligne
matrix[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [ ]:
#shape	(2, 3, 4)	dimensions
#rank	3	nombre d’axes
#size	24	nombre total d’éléments

In [27]:
#manipulations des tensors
tensor = tf.constant([[10,7], [7,10]])
tensor*50

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[500, 350],
       [350, 500]], dtype=int32)>

In [28]:
# multiplication des matrices
# matrice similaires
tensor@tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[149, 140],
       [140, 149]], dtype=int32)>

In [36]:
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
Y.ndim

2

In [37]:
X*Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7, 16],
       [27, 40],
       [55, 72]], dtype=int32)>

In [38]:
# reshape des matrices
X @ tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [39]:
# Transposer
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

In [40]:
# multiplication des matrices (autres manière de faire la multiplication de matrices)
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
# Autres formule
tf.matmul(a=X,b=Y,transpose_a=True, transpose_b=False)

In [41]:
# changer le type de variable
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [42]:
C = tf.constant([7, 10])
C.dtype

tf.int32

In [ ]:
# réduire le type de variable
B = tf.cast(B, dtype=tf.float16)
B

In [43]:
# Absolute value for tensors
D = tf.constant([-7, -10])
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [46]:
import numpy as np
E = tf.constant(np.random.randint(low = 0, high = 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([69, 87, 99, 94, 77, 49, 65, 81, 98,  9, 29, 37, 81, 55, 40, 42, 74,
       17, 54, 66, 35, 85, 86, 14, 53, 90, 28, 12,  6, 16, 71, 57, 31, 11,
       97, 16, 78, 50,  9, 24, 62, 99, 25,  8, 88, 10, 36, 92, 83, 15])>

In [ ]:
# trouver le minimum de mon tenseur
tf.reduce_min(E)

In [ ]:
# trouver le maximum
tf.reduce_max(E)

In [ ]:
# trouver la somme
tf.reduce_sum(E)

In [47]:
#Utilisation de Argmax (trouver l'index de la valeur maximale dans le tensuer)

tf.argmax(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [ ]:
#Utilisation de Argmin
tf.argmin(E)

In [48]:
#SQUEEZE (reduire des dimensions)
G = tf.constant(np.random.randint(0, 100, 50), shape=(1, 1, 1, 1,50))
G.shape, G.ndim

(TensorShape([1, 1, 1, 1, 50]), 5)

In [49]:
# enlever les dimensions de type 1 (par defaut, squeeze retire toutes les dimensions 1)
G_squeezed = tf.squeeze(G)
G_squeezed.shape, G_squeezed.ndim


(TensorShape([50]), 1)

In [50]:
# one hot encoding
liste = [0, 1, 2, 3]
# encoder les valeurs de mon tenseur, la valeur de depth depends du nombre d'élements dans le tenseur
tf.one_hot(liste, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [51]:
# matrice au carrée
H = tf.constant(np.arange(1, 10))
H

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [52]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [53]:
# transformer un tenseur en numpy array
np.array(H), type(np.array(H))

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), numpy.ndarray)

In [54]:
# trouver l'accés à mes GPU
import tensorflow as tf
print(tf.config.list_physical_devices('GPU'))

[]


In [55]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found
