In [ ]:
import torch

In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
# création des vecteurs
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
# création des matrices
matrix = torch.tensor([[7,8],
                      [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
# création des tenseurs (tenseurs de dimensions strictement supérieur à 2)
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
# random_tensor
# rand (distribution normal entre 0 et 1)
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[0.0378, 0.8901, 0.6225, 0.6112],
         [0.2475, 0.2644, 0.6865, 0.9198],
         [0.8129, 0.8094, 0.1162, 0.9009]]),
 torch.float32)

In [ ]:
zeros = torch.zeros(size=(3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [ ]:
ones = torch.ones(size=(3,4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [ ]:
# range de tenseur
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
torch.range(0, 10)

/tmp/ipython-input-1549641488.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
# datatypes avec pytorch
# device = None permet de dire d'utiliser l'appareil par défaut pour faire le calcul donc le CPU, pour préciser d'utiliser le GPU on precise CUDA
# requires_grad = None, ne sauvegarde pas les donnéess de mon tenseur, il sera à true lorsque nous serons dans l'entrainement d'un modèle par exemple
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = None, device=None, requires_grad=False)
float_32_tensor



tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype, float_32_tensor.device, float_32_tensor.shape
# INFORMATIONS UTILES POUR LES TENSEURS

(torch.float32, device(type='cpu'), torch.Size([3]))

In [ ]:
# Manipulation sur les tenseurs
TENSOR = torch.tensor([1,2,3])
TENSOR + 10

tensor([11, 12, 13])

In [ ]:
# Manipulation sur les tenseurs
TENSOR = torch.tensor([1,2,3])
TENSOR / 10

tensor([0.1000, 0.2000, 0.3000])

In [ ]:
# multiplication
TENSOR = torch.tensor([1,2,3])
torch.multiply(TENSOR, 10)

tensor([10, 20, 30])

In [ ]:
TENSOR * TENSOR

tensor([1, 4, 9])

In [ ]:
# matrice multiplication
torch.matmul(TENSOR, TENSOR)

tensor(14)

In [ ]:
x = torch.arange(0,100,5)
x.type(torch.float32).mean()

tensor(47.5000)

In [ ]:
x.sum()

tensor(950)

In [ ]:
tensor_int8 = TENSOR.type(torch.int8)
tensor_int8

tensor([1, 2, 3], dtype=torch.int8)

In [ ]:
# reshape des données
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [ ]:
# ajouter une dimension dans le tenseur
x_reshaped = x.reshape(1,7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [ ]:
# descendre en dimension
# Squeezedimension
x_squeezed = x_reshaped.squeeze()
x_squeezed, x_squeezed.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [ ]:
# transformer les array en tenseurs
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# je veux m'assure que torch voit ma carte graphique
torch.cuda.is_available()

False

In [ ]:
# comment j'envoie les tenseurs à ma carte graphique
# choix de la carte graphique
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [ ]:
tensor2 = torch.tensor([1,2,3])
print(tensor2, tensor2.device)
tensor2.device

tensor([1, 2, 3]) cpu


device(type='cpu')

In [ ]:
# moved tensor to gpu
tensor_on_gpu = tensor2.to(device)
tensor_on_gpu.device

device(type='cpu')

In [ ]:
# j'aimerais ramener au CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])